module.exports = {
    beforeEach: browser => {
        browser.url('https://www.yoodlize.com/')
    },
    after: browser => {
        browser
            .end()
    },
    'See All Functonality': browser => {
        browser
            .useXpath()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[1]')
            .verify.containsText('//div[contains(text(),"Recreational Vehicles")]', 'Recreational Vehicles')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[2]')
            .verify.containsText('//div[contains(text(),"Outdoor Gear")]', 'Outdoor Gear')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[3]')
            .verify.containsText('//div[contains(text(),"Electronics")]', 'Electronics')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[4]')
            .verify.containsText('//div[contains(text(),"Party & Wedding Equipment")]', 'Party & Wedding Equipment')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[5]')
            .verify.containsText('//div[contains(text(),"Tools")]', 'Tools')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[6]')
            .verify.containsText('//div[contains(text(),"Clothing")]', 'Clothing')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[7]')
            .verify.containsText('//div[contains(text(),"Home and Kitchen")]', 'Home and Kitchen')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[8]')
            .verify.containsText('//div[contains(text(),"Toys and Games")]', 'Toys and Games')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[9]')
            .verify.containsText('//div[contains(text(),"Lawn and Garden")]', 'Lawn and Garden')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[10]')
            .verify.containsText('//div[contains(text(),"Sporting Equipment")]', 'Sporting Equipment')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[11]')
            .verify.containsText('//div[contains(text(),"DVDs")]', 'DVDs')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[12]')
            .verify.containsText('//div[contains(text(),"Venues")]', 'Venues')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[13]')
            .verify.containsText('//div[contains(text(),"Music")]', 'Music')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[14]')
            .verify.containsText('//div[contains(text(),"Business Equipment")]', 'Business Equipment')
            .back()
            .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[15]')
            .verify.containsText('//div[contains(text(),"Misc")]', 'Misc')
            .back()

    },
    'Icons Functonality': browser => {
        browser
            .useXpath()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[1]')
            .verify.containsText('//div[contains(text(),"Tools")]', 'Tools')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[2]')
            .verify.containsText('//div[contains(text(),"Outdoor Gear")]', 'Outdoor Gear')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[3]')
            .verify.containsText('//div[contains(text(),"Electronics")]', 'Electronics')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[4]')
            .verify.containsText('//div[contains(text(),"Party & Wedding")]', 'Party & Wedding')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[5]')
            .verify.containsText('//div[contains(text(),"Recreational Vehicles")]', 'Recreational Vehicles')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[6]')
            .verify.containsText('//div[contains(text(),"Clothing")]', 'Clothing')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[7]')
            .verify.containsText('//div[contains(text(),"Home and Kitchen")]', 'Home and Kitchen')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[8]')
            .verify.containsText('//div[contains(text(),"Toys and Games")]', 'Toys and Games')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[9]')
            .verify.containsText('//div[contains(text(),"Lawn and Garden")]', 'Lawn and Garden')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[10]')
            .verify.containsText('//div[contains(text(),"Sporting")]', 'Sporting')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[11]')
            .verify.containsText('//div[contains(text(),"DVDs")]', 'DVDs')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[12]')
            .verify.containsText('//div[contains(text(),"Venues")]', 'Venues')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[13]')
            .verify.containsText('//div[contains(text(),"Music")]', 'Music')
            .back()
            .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[14]')
            .verify.containsText('//div[contains(text(),"Misc")]', 'Misc')
            .back()
    }
}

